### ISSUE TITLE
Kotlin 协程支持

### ISSUE THREAD

**Issue by syxc** [troyzhxu/okhttps#75]
有考虑支持结合 Kotlin 协程一起使用的计划么？
结合 Kotlin 协程使用起来应该会更方便。

**Comment by lukelmouse-github** [comment]
建议看Net，比这款框架优雅多了
https://github.com/liangjingkanji/Net

**Comment by syxc** [comment]
> 建议看Net，比这款框架优雅多了
> https://github.com/liangjingkanji/Net
Net 有关注，不过 Net 是 for Android，这个通用的，Android、服务端都可以，也好用。

**Comment by syxc** [comment]
> 建议看Net，比这款框架优雅多了
> https://github.com/liangjingkanji/Net

Net 有关注，不过 Net 是 for Android，这个通用的，Android、服务端都可以，也好用。
